#!/usr/bin/env node

var fs = require("fs");

function readCommitMsg(callback) {
	fs.readFile(process.argv[2], 'utf8', function (err, content) {
		if (err) 
			return callback(err);
		
		callback(content);
	});
}

function isTicketPresent(content) {
	//var isGood = /\[ref: (\d+)\]/.test(content);
	var isGood = /AIS-(\d+)/.test(content);
	if (!isGood)
		console.warn("Ticket WAS NOT present");

	return isGood; 
}

readCommitMsg(function (content) {
	if (!isTicketPresent(content))
		process.exit(1);

	process.exit(0);
})
